services:
  mysql:
    image: mariadb:10.5
    # image: mysql:8.0 # 囲み文字を使用する場合
    volumes:
      - mysql-db:/var/lib/mysql
    environment:
      MYSQL_USER: epgstation
      MYSQL_PASSWORD: epgstation
      MYSQL_ROOT_PASSWORD: epgstation
      MYSQL_DATABASE: epgstation
      TZ: "Asia/Tokyo"
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --performance-schema=false --expire_logs_days=1 # for mariadb
    # command: --character-set-server=utf8mb4 --collation-server=utf8mb4_0900_as_ci --performance-schema=false --expire_logs_days=1 --default-authentication-plugin=mysql_native_password # for myql
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  epgstation:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./config:/app/config
      - ./data:/app/data
      - ./thumbnail:/app/thumbnail
      - ./logs:/app/logs
      - ./epgs-to-discord/config.toml:/root/.config/epgs-to-discord/config.toml
      - ./recorded:/app/recorded
    environment:
      TZ: "Asia/Tokyo"
    depends_on:
      - mysql
    ports:
      - "8888:8888"
      - "8889:8889"
    restart: always

volumes:
  mysql-db:
